spring.application.name=aop

# ===============================
# SQL SERVER (Primary Database)
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/AOP?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=123456@abcd
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


# ===============================
# MONGODB ATLAS (Secondary Database)
# ===============================
# Format: mongodb+srv://<username>:<password>@<cluster-url>/<database-name>?retryWrites=true&w=majority
spring.data.mongodb.uri=mongodb+srv://anshparnami_db_user:lO2f5zZg2ixrgMT4@cluster0.ztmm3ja.mongodb.net/AOP_assignment?appName=Cluster0

# Optional: To see Mongo logs in console
logging.level.org.springframework.data.mongodb=DEBUG